### ISSUE TITLE
RayGun4WP root menu appears to non-administrator roles (e.g. editors)

### ISSUE THREAD

**Issue by aidanlane** [MindscapeHQ/raygun4wordpress#9]
You can't actually access anything as a non-admin, but it's there nonetheless.
We have many non-technical users and we don't wish to show this.

We can fork, fix and send a pull request if you like.

![image](https://cloud.githubusercontent.com/assets/1817949/7427234/5d361ad4-f01a-11e4-99a9-14735a840415.png)

Thanks for a great plugin and service though!

**Comment by fundead** [comment]
Cheers for reporting this one - a PR would be much appreciated and we can get that released promptly if you do manage to send one through. If not I will be able to take a look at it in the near future.

Regards,

Callum Gavin
Mindscape Limited

**Comment by aidanlane** [comment]
Great, thanks @fundead, I'll get one of my devs on to it ASAP.

**Comment by johnliman** [comment]
Hi @fundead, I work @aidanlane. The code that is showing the Raygun4WP menu for non-administrator user is the following:
```php
function rg4wp_external()
  {
    global $submenu;
    $submenu['rg4wp'][500] = array('Open raygun.io', 'administrator', 'javascript:window.open("http://raygun.io?utm_source=wordpress&utm_medium=admin&utm_campaign=raygun4wp");return false;');
  }
```

It looks like the code intends to promote Raygun for non-administrator users by opening raygun.io webpage referencing its campaign id when it is clicked.  Currently, when it is clicked for non-administrator the javascript has an error shown in Chrome console (`Uncaught SyntaxError: Illegal return statement`), thus it does not do anything.  If the `return false;` statement is removed, it will then open up a new tab/window showing http://raygun.io website.

However, the Raygun is only understandable by Wordpress System Administrator because it is about system error tracking, the authors/editors who are just editing/posting content will not be able to configure Raygun.  With regards to acknowledgement/marketing campaign of Raygun for system administrators, the About page is already sufficient to provide for it.  Therefore, it makes sense not to show the Raygun4WP menu for non system administrator.

If it is ok, I will raise a PR not to add_action for rg4wp_external.

**Comment by fundead** [comment]
Hi John,

Good spotting, you're correct in stating that Raygun should only be visible by the administrator. I believe the intent was to set the capability for that link to the Administrator role anyway and therefore not viewable by non-admins (as it is being added to admin_menu).

I have located references that state the capability string may be case-sensitive (i.e `Administrator` as the 2rd array element above, and the 3rd/4th params for add_menu_page/add_submenu_page respectively). If the rg4wp menu item is being added with the incorrect role and causing it (and the corresponding external link) to be displayed for non-admins getting this tightened up would be the best way forward. The cause of this issue could alternately be that the `administrator` role has been removed or renamed on your installation - it might be worthwhile to quickly check that.

Let me know if changing the case fixes the scoping issue.

**Comment by johnliman** [comment]
I have quickly checked that my installation has administrator role.  I also have checked if I login as administrator, I could see the Raygun4WP menu (even after I remove `rg4wp_external()` function), when I clicked on it, and it will not trigger the open window js as mentioned above but it will trigger the 'About' page (as this is the first item in the submenu).  The `rg4wp_external()` function will only be triggered for non-admins.

I also have tried changing `administrator` to `Administrator it does not have any effect, so it is not case sensitive check.

**Comment by aidanlane** [comment]
Thanks for checking :) We'll give them a little more time and then let's give them a 'gentle reminder' ;)

**Comment by fundead** [comment]
Thanks for checking that - we ran out of time to repro the cause of the inconsistency this week but it's queued up to be looked at on Monday. Will let you know the results.

**Comment by aidanlane** [comment]
Fantastic, thanks Callum!

**Comment by fundead** [comment]
One more thing - what version of WP are you using?

**Comment by aidanlane** [comment]
Currently 4.1.5, but moving to 4.2.x soon...

**Comment by fundead** [comment]
Thanks for that - looks like the API behavior has changed since the function was implemented, and since as you note the About page takes care of the use case, we've got a PR here that removes the offending link: https://github.com/MindscapeHQ/raygun4wordpress/pull/11.

If you are able to verify this branch could you confirm there are no issues with the fix (tested with a fresh 4.2.2 installation here). All going we'll look at getting this rolled out in a new release shortly.

**Comment by aidanlane** [comment]
Brilliant, thanks Callum!

@johnliman, can you check, thanks

**Comment by fundead** [comment]
This one appears to be working well for us so we'll get it out the door as v1.5.2.

Hope Raygun continues to be useful for your team!

Regards,

Callum Gavin
Mindscape Limited

**Comment by aidanlane** [comment]
Thanks @fundead, we really appreciate this being fixed in the official repo, as I'm sure many others are too.

Btw, the RaygunPHP and RaygunJS deps haven't been updated. As we already use Composer, should we perhaps just use them instead of this plugin so that they're always up to date?

Btw2, the 'Compatible up to' WordPress version on Wordpress.org could be updated to 4.2.2- it's still at 3.6.1!?

...sorry to be a pain :)

**Comment by fundead** [comment]
Thanks for reporting those, I've queued up the dependencies to be bumped in the next release. In the meantime Composer is probably the best way to grab them immediately. I'll also bump the compatible version, good spotting!

**Comment by aidanlane** [comment]
You're a champion, thanks @fundead!
